/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.DefaultListModel;
import uni.aed.libreria.Library;

/**
 *
 * @author AndreP
 */
public class FrmBiblioteca extends javax.swing.JFrame {
    Library libreria;
//    private DefaultListModel<String> modeloLibros;
//    private DefaultListModel<String> modeloPrestamos;
    
    /**
     * Creates new form FrmBiblioteca
     */
    public FrmBiblioteca() {
        initComponents();
        // Inicializa la libreria
        libreria = new Library();
        
        // Inicializa los modelos:
//        modeloLibros = new DefaultListModel<>();
//        modeloPrestamos = new DefaultListModel<>();
//        
//        listaLibros.setModel(modeloLibros);
//        listaPrestamoLibros.setModel(modeloPrestamos);
        
        // Agregamos botones al grupo de botones
        bttnGroupOperaciones.add(rbAgregarLibro);
        bttnGroupOperaciones.add(rbRegistrarDevolucion);
        bttnGroupOperaciones.add(rbRegistrarPrestamo);
        
        // Por defecto estará activado el rbAgregarLibro
        rbAgregarLibro.setSelected(true);
        txtLibro.setEnabled(true);
        txtAutor.setEnabled(true);
        txtUsuario.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttnGroupOperaciones = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        jPSubFrames = new javax.swing.JPanel();
        txtFieldPrestamos = new javax.swing.JTextField();
        txtFieldLibros = new javax.swing.JTextField();
        jPoperaciones = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rbRegistrarDevolucion = new javax.swing.JRadioButton();
        rbRegistrarPrestamo = new javax.swing.JRadioButton();
        rbAgregarLibro = new javax.swing.JRadioButton();
        jPEntradaValores = new javax.swing.JPanel();
        lblLibro = new javax.swing.JLabel();
        txtLibro = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        lblAutor = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        bttnMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("GESTION DE BIBLIOTECA");

        javax.swing.GroupLayout jPSubFramesLayout = new javax.swing.GroupLayout(jPSubFrames);
        jPSubFrames.setLayout(jPSubFramesLayout);
        jPSubFramesLayout.setHorizontalGroup(
            jPSubFramesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPSubFramesLayout.createSequentialGroup()
                .addContainerGap(315, Short.MAX_VALUE)
                .addComponent(txtFieldPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(jPSubFramesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPSubFramesLayout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(txtFieldLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(310, Short.MAX_VALUE)))
        );
        jPSubFramesLayout.setVerticalGroup(
            jPSubFramesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPSubFramesLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(txtFieldPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPSubFramesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPSubFramesLayout.createSequentialGroup()
                    .addContainerGap(47, Short.MAX_VALUE)
                    .addComponent(txtFieldLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(33, 33, 33)))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Operaciones");

        rbRegistrarDevolucion.setText("Registrar Devolucion");
        rbRegistrarDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRegistrarDevolucionActionPerformed(evt);
            }
        });

        rbRegistrarPrestamo.setText("Registrar Prestamo");
        rbRegistrarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRegistrarPrestamoActionPerformed(evt);
            }
        });

        rbAgregarLibro.setText("Agregar Libro");
        rbAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAgregarLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPoperacionesLayout = new javax.swing.GroupLayout(jPoperaciones);
        jPoperaciones.setLayout(jPoperacionesLayout);
        jPoperacionesLayout.setHorizontalGroup(
            jPoperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPoperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addComponent(rbAgregarLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(rbRegistrarPrestamo)
                .addGap(52, 52, 52)
                .addComponent(rbRegistrarDevolucion)
                .addGap(42, 42, 42))
        );
        jPoperacionesLayout.setVerticalGroup(
            jPoperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPoperacionesLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPoperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(rbAgregarLibro)
                    .addComponent(rbRegistrarPrestamo)
                    .addComponent(rbRegistrarDevolucion))
                .addGap(10, 10, 10))
        );

        lblLibro.setText("Ingrese nombre del libro:");

        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorActionPerformed(evt);
            }
        });

        lblAutor.setText("Ingrese nombre del autor:");

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        lblUsuario.setText("Ingrese nombre de usuario:");

        javax.swing.GroupLayout jPEntradaValoresLayout = new javax.swing.GroupLayout(jPEntradaValores);
        jPEntradaValores.setLayout(jPEntradaValoresLayout);
        jPEntradaValoresLayout.setHorizontalGroup(
            jPEntradaValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEntradaValoresLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPEntradaValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAutor)
                    .addComponent(lblUsuario)
                    .addComponent(lblLibro))
                .addGap(36, 36, 36)
                .addGroup(jPEntradaValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPEntradaValoresLayout.setVerticalGroup(
            jPEntradaValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEntradaValoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPEntradaValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLibro)
                    .addComponent(txtLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPEntradaValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutor)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPEntradaValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        bttnMostrar.setText("Mostrar");
        bttnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPoperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPEntradaValores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPSubFrames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(bttnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(jPoperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPEntradaValores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttnMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jPSubFrames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorActionPerformed

    private void rbAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAgregarLibroActionPerformed
        txtLibro.setEnabled(true);
        txtAutor.setEnabled(true);
        txtUsuario.setEnabled(false);
        clearFields();
    }//GEN-LAST:event_rbAgregarLibroActionPerformed

    private void rbRegistrarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRegistrarPrestamoActionPerformed
        txtLibro.setEnabled(true);
        txtAutor.setEnabled(true);
        txtUsuario.setEnabled(true);
        clearFields();
    }//GEN-LAST:event_rbRegistrarPrestamoActionPerformed

    private void rbRegistrarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRegistrarDevolucionActionPerformed
        txtLibro.setEnabled(true);
        txtAutor.setEnabled(true);
        txtUsuario.setEnabled(true);
        clearFields();
    }//GEN-LAST:event_rbRegistrarDevolucionActionPerformed
    private void clearFields(){
        txtLibro.setText("");
        txtAutor.setText("");
        txtUsuario.setText("");
    }
    private void bttnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnMostrarActionPerformed
        
        try{
            if (rbAgregarLibro.isSelected()) {
                // Agregar un libro
                String autor = txtAutor.getText();
                String titulo = txtLibro.getText();
                libreria.includeBook(autor, titulo);

                // Actualizar la lista de libros
                updateListaLibros();

            } else if (rbRegistrarPrestamo.isSelected()) {
                // Registrar un préstamo
                String usuario = txtUsuario.getText();
                String autor = txtAutor.getText();
                String titulo = txtLibro.getText();
                libreria.checkOutBook(usuario, autor, titulo);

                // Actualizar las listas
                updateListaLibros();
                updateListaPrestamos();

            } else if (rbRegistrarDevolucion.isSelected()) {
                // Registrar una devolución
                String usuario = txtUsuario.getText();
                String autor = txtAutor.getText();
                String titulo = txtLibro.getText();
                libreria.returnBook(usuario, autor, titulo);

                // Actualizar las listas
                updateListaLibros();
                updateListaPrestamos();
            }

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        } finally {
            txtLibro.requestFocus();
        }
    }//GEN-LAST:event_bttnMostrarActionPerformed
    private void updateListaLibros() {
//       modeloLibros.clear();
//       modeloLibros.addElement(libreria.getBooksString());
    txtFieldLibros.setText(libreria.getBooksString());

   }

   private void updateListaPrestamos() {
//       modeloPrestamos.clear();
//       modeloPrestamos.addElement(libreria.getPeopleString());
        txtFieldPrestamos.setText(libreria.getPeopleString());
   }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBiblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bttnGroupOperaciones;
    private javax.swing.JButton bttnMostrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPEntradaValores;
    private javax.swing.JPanel jPSubFrames;
    private javax.swing.JPanel jPoperaciones;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblLibro;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JRadioButton rbAgregarLibro;
    private javax.swing.JRadioButton rbRegistrarDevolucion;
    private javax.swing.JRadioButton rbRegistrarPrestamo;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtFieldLibros;
    private javax.swing.JTextField txtFieldPrestamos;
    private javax.swing.JTextField txtLibro;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
